/**
 * Shared game-entity image resolver for Boss Drops and Crafting Planner.
 */

const CDN = 'https://palpedia.azrocdn.com';

const ITEM_IMAGE_MAP: Record<string, string> = {
  Arrow: 'items/T_itemicon_Arrow.png',
  Berries: 'items/T_itemicon_Food_Berries.png',
  BerrySeeds: 'items/T_itemicon_BerrySeeds.png',
  Bone: 'items/T_itemicon_Material_Bone.png',
  Cake: 'items/T_itemicon_Food_Cake.png',
  CarbonFiber: 'items/T_itemicon_Material_CarbonFiber.png',
  CoralumIngot: 'items/T_itemicon_Material_ManganeseIngot.png',
  CoralumOre: 'items/T_itemicon_Material_ManganeseOre.png',
  Cloth: 'items/T_itemicon_Material_Cloth.png',
  Cloth2: 'items/T_itemicon_Material_Cloth2.png',
  Coal: 'items/T_itemicon_Material_Coal.png',
  CopperIngot: 'items/T_itemicon_Material_CopperIngot.png',
  CopperOre: 'items/T_itemicon_Material_CopperOre.png',
  CrudeOil: 'items/T_itemicon_Material_CrudeOil.png',
  Diamond: 'items/T_itemicon_Material_Diamond.png',
  DogCoin: 'items/T_itemicon_Accessory_DogCoin.png',
  Egg: 'items/T_itemicon_Food_Egg.png',
  ElectricOrgan: 'items/T_itemicon_Material_ElectricOrgan.png',
  ExpBoost_04: 'items/T_itemicon_ExpBoost_04.png',
  Fiber: 'items/T_itemicon_Material_Fiber.png',
  FireOrgan: 'items/T_itemicon_Material_FireOrgan.png',
  FlameOrgan: 'items/T_itemicon_Material_FireOrgan.png',
  Gunpowder: 'items/T_itemicon_Material_Gunpowder2.png',
  Gunpowder2: 'items/T_itemicon_Material_Gunpowder2.png',
  Herbs: 'items/T_itemicon_Food_Herbs.png',
  HighQualityPalOil: 'items/T_itemicon_Material_PalOil.png',
  Honey: 'items/T_itemicon_Material_Honey.png',
  Horn: 'items/T_itemicon_Material_Horn.png',
  IceOrgan: 'items/T_itemicon_Material_IceOrgan.png',
  Ingot: 'items/T_itemicon_Material_CopperIngot.png',
  IronIngot: 'items/T_itemicon_Material_IronIngot.png',
  Leather: 'items/T_itemicon_Material_Leather.png',
  LettuceSeeds: 'items/T_itemicon_LettuceSeeds.png',
  Meat_BerryGoat: 'items/T_itemicon_Food_Meat_BerryGoat.png',
  Meat_Boar: 'items/T_itemicon_Food_Meat_Boar.png',
  Meat_ChickenPal: 'items/T_itemicon_Food_Meat_ChickenPal.png',
  Meat_CowPal: 'items/T_itemicon_Food_Meat_CowPal.png',
  Meat_Deer: 'items/T_itemicon_Food_Meat_Deer.png',
  Meat_Eagle: 'items/T_itemicon_Food_Meat_Eagle.png',
  Meat_GrassMammoth: 'items/T_itemicon_Food_Meat_GrassMammoth.png',
  Meat_IceDeer: 'items/T_itemicon_Food_Meat_IceDeer.png',
  Meat_Kelpie: 'items/T_itemicon_Food_Meat_Kelpie.png',
  Meat_LazyCatfish: 'items/T_itemicon_Food_Meat_LazyCatfish.png',
  Meat_SakuraSaurus: 'items/T_itemicon_Food_Meat_SakuraSaurus.png',
  Meat_SheepBall: 'items/T_itemicon_Food_Meat_SheepBall.png',
  MeteorDrop: 'items/T_itemicon_Material_MeteorDrop.png',
  Milk: 'items/T_itemicon_Food_Milk.png',
  Money: 'items/T_itemicon_Material_Money.png',
  Mushroom: 'items/T_itemicon_Food_Mushroom.png',
  Nail: 'items/T_itemicon_Material_MachineParts.png',
  MachineParts: 'items/T_itemicon_Material_MachineParts.png',
  Narcotic: 'items/T_itemicon_Material_Narcotic.png',
  Opium: 'items/T_itemicon_Material_Opium.png',
  Ore: 'items/T_itemicon_Material_CopperOre.png',
  Chromite: 'items/T_itemicon_Material_Chromium.png',
  Chromium: 'items/T_itemicon_Material_Chromium.png',
  Hexolite: 'items/T_itemicon_Material_StainlessSteel.png',
  StainlessSteel: 'items/T_itemicon_Material_StainlessSteel.png',
  HexoliteQuartz: 'items/T_itemicon_Material_RainbowCrystal.png',
  RainbowCrystal: 'items/T_itemicon_Material_RainbowCrystal.png',
  CryogenicCoolant: 'items/T_itemicon_Material_Bio_Coolant.png',
  Bio_Coolant: 'items/T_itemicon_Material_Bio_Coolant.png',
  CorrosiveSolvent: 'items/T_itemicon_Material_Corrosive_Solvent.png',
  Corrosive_Solvent: 'items/T_itemicon_Material_Corrosive_Solvent.png',
  PalFluid: 'items/T_itemicon_Material_PalFluid.png',
  PalItem_CaptainPenguin: 'items/T_itemicon_PalItem_CaptainPenguin.png',
  PalItem_CatMage: 'items/T_itemicon_PalItem_CatMage.png',
  PalItem_ColorfulBird: 'items/T_itemicon_PalItem_ColorfulBird.png',
  PalItem_LizardMan: 'items/T_itemicon_PalItem_LizardMan.png',
  PalItem_MopBaby: 'items/T_itemicon_PalItem_MopBaby.png',
  PalItem_NegativeOctopus: 'items/T_itemicon_PalItem_NegativeOctopus.png',
  PalItem_PinkRabbit: 'items/T_itemicon_PalItem_PinkRabbit.png',
  PalItem_PlantSlime: 'items/T_itemicon_PalItem_PlantSlime.png',
  PalItem_RaijinDaughter: 'items/T_itemicon_PalItem_RaijinDaughter.png',
  PalItem_ToSell_04: 'items/T_itemicon_PalItem_ToSell_04.png',
  PalOil: 'items/T_itemicon_Material_PalOil.png',
  PalUpgradeStone: 'items/T_itemicon_PalUpgradeStone.png',
  PalUpgradeStone2: 'items/T_itemicon_PalUpgradeStone2.png',
  PalUpgradeStone3: 'items/T_itemicon_PalUpgradeStone3.png',
  Pal_crystal_S: 'items/T_itemicon_Material_Pal_crystal_S.png',
  Plastic: 'items/T_itemicon_Material_Plastic.png',
  Polymer: 'items/T_itemicon_Material_Polymer.png',
  Poppy: 'items/T_itemicon_Food_Poppy.png',
  PureQuartz: 'items/T_itemicon_Material_Quartz.png',
  Quartz: 'items/T_itemicon_Material_Quartz.png',
  Ruby: 'items/T_itemicon_Material_Ruby.png',
  Sapphire: 'items/T_itemicon_Material_Sapphire.png',
  Spear_QueenBee: 'items/T_itemicon_Weapon_Spear_QueenBee.png',
  StatusPointResetSan: 'items/T_itemicon_StatusPointResetSan.png',
  StealIngot: 'items/T_itemicon_Material_StealIngot.png',
  Stone: 'items/T_itemicon_Material_Stone.png',
  Sulfur: 'items/T_itemicon_Material_Sulfur.png',
  Sweet: 'items/T_itemicon_Food_Sweet.png',
  TechnologyBook_G1: 'items/T_itemicon_TechnologyBook_G1.png',
  TechnologyBook_G2: 'items/T_itemicon_TechnologyBook_G2.png',
  TomatoSeeds: 'items/T_itemicon_TomatoSeeds.png',
  TreasureBoxKey01: 'items/T_itemicon_TreasureBoxKey01.png',
  TreasureBoxKey02: 'items/T_itemicon_TreasureBoxKey02.png',
  Venom: 'items/T_itemicon_Material_Venom.png',
  VenomGland: 'items/T_itemicon_Material_VenomGland.png',
  WheatSeeds: 'items/T_itemicon_WheatSeeds.png',
  Wood: 'items/T_itemicon_Material_Wood.png',
  Wool: 'items/T_itemicon_Material_Wool.png',
  Charcoal: 'items/T_itemicon_Material_Charcoal.png',
  Cement: 'items/T_itemicon_Material_Cement.png',
  Computer: 'items/T_itemicon_Material_Computer.png',
  Bio_Battery: 'items/T_itemicon_Material_Bio_Battery.png',
  ElectronicCircuit: 'items/T_itemicon_Material_ElectronicCircuit.png',
  PaldiumFragment: 'items/T_itemicon_Material_Pal_crystal_S.png',
  BlastFurnace4: 'buildings/T_icon_buildObject_BlastFurnace4.png',
  ElectricFurnace: 'buildings/T_icon_buildObject_BlastFurnace3.png',
  Factory2: 'buildings/T_icon_buildObject_Factory_Hard_03.png',
  WeaponFactory2: 'buildings/T_icon_buildObject_WeaponFactory_Dirty_03.png',
  SphereFactory2: 'buildings/T_icon_buildObject_SphereFactory_Black_03.png',
  Refrigerator: 'buildings/T_icon_buildObject_Refrigerator.png',
  ElectricKitchen: 'buildings/T_icon_buildObject_ElectricKitchen.png',
  MedicineFactory2: 'buildings/T_icon_buildObject_MedicineFacility_02.png',
  Chest3: 'buildings/T_icon_buildObject_ItemChest_04.png',
  SphereFactory3: 'buildings/T_icon_buildObject_SphereFactory_Black_04.png',
  MissileLauncher: 'buildings/T_icon_buildObject_efenseBulletLauncher_Missile.png',
};

export function getGameEntityImageUrl(iconNameOrId: string): string {
  const path = ITEM_IMAGE_MAP[iconNameOrId];
  if (path) return `${CDN}/${path}`;
  return `${CDN}/items/T_itemicon_Material_${iconNameOrId}.png`;
}

/** Boss Drops-compatible alias. */
export function getItemImageUrl(itemId: string): string {
  return getGameEntityImageUrl(itemId);
}
